CREATE TABLE TBL_EXAMINATION(
EXAM_ID VARCHAR(100) PRIMARY KEY,
EXAM_CODE VARCHAR(256)  NOT NULL,
EXAM_TITLE VARCHAR(256)  NOT NULL,
EXAM_DESC VARCHAR(256)  NOT NULL,
EXAM_DATE VARCHAR(256) NOT NULL,
EXAM_TIME VARCHAR(256) NOT NULL,
EXAM_DURATION VARCHAR(256) NOT NULL
);
CREATE TABLE TBL_QUESTION(
QUESTION_ID VARCHAR(100) PRIMARY KEY,
EXAM_ID VARCHAR(100),
QUESTION_LABEL VARCHAR(100) NOT NULL,
QUESTION_DESC TEXT  NOT NULL,
ANSWER_LABEL VARCHAR(100) NOT NULL,
FOREIGN KEY (EXAM_ID) REFERENCES TBL_EXAMINATION(EXAM_ID)
);


CREATE TABLE TBL_OPTION(
OPTION_ID VARCHAR(100) PRIMARY KEY,
QUESTION_ID VARCHAR(100),
OPTION_LABEL VARCHAR(100) NOT NULL,
OPTION_DESC VARCHAR(100) NOT NULL,
FOREIGN KEY (QUESTION_ID) REFERENCES TBL_QUESTION(QUESTION_ID)
);


CREATE TABLE TBl_USER_ANSWER(
QUESTION_ID VARCHAR(256)  NOT NULL,
ANSWER_LABEL VARCHAR(5) NOT NULL,
ATTEMPT_ID VARCHAR(256) NOT NULL,
SUBMITTED_AT LONG NOT NULL
);
--EXAM_CODE VARCHAR(256) NOT NULL,
--EXAM_ID VARCHAR(256) NOT NULL,

CREATE TABLE TBL_USER_ATTEMPT(
USER_ACCOUNT_ID VARCHAR(256) NOT NULL,
ATTEMPT_ID VARCHAR(256) PRIMARY KEY,
EXAM_ID VARCHAR(256) NOT NULL,
EXAM_TYPE VARCHAR(256) NOT NULL,
STARTED_AT LONG NOT NULL,
END_AT LONG NOT NULL,
RESULT TEXT NOT NULL,
SCORE INT NOT NULL
);